version: '3.4'

services:
  messagebroker:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  yarpapigateway:
    image: smartedu-gateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile
    ports:
      - "7000:8080"
    depends_on:
      - identity.api
      - course.api
      - exam.api
      - notification.api
      - comment.api
      - payment.api

  identity.api:
    image: smartedu-identity
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MessageBroker:Host=rabbitmq://messagebroker
    volumes:
      - ./firebase:/app/firebase

  course.api:
    image: smartedu-course
    build:
      context: .
      dockerfile: Services/Course/Course.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MessageBroker:Host=rabbitmq://messagebroker
      - Redis:ConnectionString=redis:6379
    depends_on:
      - messagebroker
    volumes:
      - ./firebase:/app/firebase

  exam.api:
    image: smartedu-exam
    build:
      context: .
      dockerfile: Services/Exam/Exam.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MessageBroker:Host=rabbitmq://messagebroker
      - GrpcSettings:CourseUrl=http://course.api:8081
      - GrpcSettings:IdentityUrl=http://identity.api:8081
    depends_on:
      - messagebroker
    volumes:
      - ./firebase:/app/firebase

  notification.api:
    image: smartedu-notification
    build:
      context: .
      dockerfile: Services/Notification/Notification.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MessageBroker:Host=rabbitmq://messagebroker
      - GrpcSettings:CourseUrl=http://course.api:8081
    depends_on:
      - messagebroker
    volumes:
      - ./firebase:/app/firebase

  comment.api:
    image: smartedu-comment
    build:
      context: .
      dockerfile: Services/Comment/Comment.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./firebase:/app/firebase

  payment.api:
    image: smartedu-payment
    build:
      context: .
      dockerfile: Services/Payment/Payment.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MessageBroker:Host=rabbitmq://messagebroker
      - ConnectionStrings:DefaultConnection=Host=aws-1-ap-northeast-1.pooler.supabase.com;Port=5432;Database=postgres;Username=postgres.cgemkhxgwzdwvrwmonvr;Password=mxVeZqKjLS10DOPv;SslMode=Require;TrustServerCertificate=true
    depends_on:
      - messagebroker
