# Trigger AKS CD deploy test
apiVersion: v1
kind: Secret
metadata:
  name: smartedu-secrets
type: Opaque
stringData:
  IDENTITY_DB_CONNECTION: "YOUR_IDENTITY_DB_CONNECTION"
  PAYMENT_DB_CONNECTION: "YOUR_PAYMENT_DB_CONNECTION"
  JWT_KEY: "YOUR_JWT_KEY"
  JWT_ISSUER: "YOUR_JWT_ISSUER"
  JWT_AUDIENCE: "YOUR_JWT_AUDIENCE"
  VNPAY_HASH_SECRET: "YOUR_VNPAY_HASH_SECRET"
  MOMO_SECRET_KEY: "YOUR_MOMO_SECRET_KEY"
  PAYPAL_SECRET_KEY: "YOUR_PAYPAL_SECRET_KEY"
  FIREBASE_CREDENTIALS_JSON_COURSE: '{"type": "service_account", "project_id": "YOUR_PROJECT_ID"}'
  FIREBASE_CREDENTIALS_JSON_NOTIFICATION: '{"type": "service_account", "project_id": "YOUR_PROJECT_ID"}'
  FIREBASE_CREDENTIALS_JSON_COMMENT: '{"type": "service_account", "project_id": "YOUR_PROJECT_ID"}'
  FIREBASE_CREDENTIALS_JSON_EXAM: '{"type": "service_account", "project_id": "YOUR_PROJECT_ID"}'

